const double VALOR_INFRACAO_LEVE = 88.38;
const double VALOR_INFRACAO_MEDIA = 130.16;
const double VALOR_INFRACAO_GRAVE = 195.23;
const double VALOR_INFRACAO_GRAVISSIMA = 293.47;
const double TOLERANCIA_PBTC_BALANCA = 0.05;
